### PR TITLE
extraction base class from news and notice

### PR DESCRIPTION
**Pull request by ZhaoQi99**

### CODE REVIEW

**Comment by ZhaoQi99** [comment]
Lock by PR #18

**Comment by xiekeyi98** [comment]
This pull request **introduces 2 alerts** when merging bf6750f71181a7960488d81215e73acfe216c66a into bea4501c3d50af4df25a8c6fffaf4d6712f6f2e0 - [view on LGTM.com](https://lgtm.com/projects/g/snnucs/SNNU-SDK/rev/pr-1e3a18e28cccec1b4efdd7c1268b935e94a3204f)

**new alerts:**

* 1 for Wrong number of arguments in a call
* 1 for Wrong number of arguments in a class instantiation

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by xiekeyi98** [comment]
This pull request **introduces 2 alerts** when merging bf6750f71181a7960488d81215e73acfe216c66a into 96eeabd448f39b1a003273e382ebab83b48c734d - [view on LGTM.com](https://lgtm.com/projects/g/snnucs/SNNU-SDK/rev/pr-82746781202d311cd37e379b84986f0e2fcf4a97)

**new alerts:**

* 1 for Wrong number of arguments in a call
* 1 for Wrong number of arguments in a class instantiation

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ZhaoQi99** [comment]
close #13

**Comment by xiekeyi98** [comment]
This pull request **introduces 2 alerts** when merging d7569d3f6f6d6633ff8bb992c3c939913351aef4 into 3e5280741171d6c5aa5127f9656e37a69687dbd7 - [view on LGTM.com](https://lgtm.com/projects/g/snnucs/SNNU-SDK/rev/pr-34af40bd864c3e585d6e318aacabddfd1fb53685)

**new alerts:**

* 1 for Wrong number of arguments in a call
* 1 for Wrong number of arguments in a class instantiation

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
